CREATE DATABASE IF NOT EXISTS Customers;
USE Customers;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Customers (
  Id INTEGER UNSIGNED NOT NULL,
  CustID INTEGER UNSIGNED NOT NULL,
  CName VARCHAR(45) NOT NULL,
  PRIMARY KEY (Id)
);

INSERT INTO Customers VALUES (1,4711,"John Klabuster");
INSERT INTO Customers VALUES (2,331777,"Gerald Bostock");
