CREATE DATABASE IF NOT EXISTS Users;
USE Users;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  Id INTEGER UNSIGNED NOT NULL,
  UName VARCHAR(45) NOT NULL,
  Passwd VARCHAR(45) NOT NULL,
  PRIMARY KEY (Id)
);

INSERT INTO Users VALUES (1,"Paul","pass");
INSERT INTO Users VALUES (2,"Ringo","s3cr3t");
